Protobuffer generation: handle many parameters
Apodini/Apodini pull request #131
Opened 2021-01-14 15:26 UTC by nityanandaz

# Protobuffer generation: handle many parameters

Closes #62

## Implications

`Runtime.PropertyInfo` is overridden in Apodini

## Testing

Tests cover new differentiation

2021-01-19 18:20 UTC, moritzschuell requested changes
For some reason, this branch's `TestWebService` does not work for me 🤔
It fails in `EnrichedInfo.swift` line 58 with the `preconditionFailure(errorDescription)`:

`Thread 1: Fatal error: couldNotGetTypeInfo(type: () -> Swift.UInt, kind: Runtime.Kind.function)`

I tried clean-building and also replacing any `Int`s or `UInt`s in the `TestWebService` with their fixed-width counterparts, but it still keeps crashing.

Tests are passing like a charm, though.

2021-01-25 15:04 UTC, lschlesinger approved these changes
I find the `propertyInfo` refactoring reasonable 👍 Added comments regarding the string replacement in `compatibleType` and a link to a PR which I think is related to your `.edit()` procedure. If so, this can also be addressed in a separate PR - this one is good to go I would say 😉

2021-01-25 15:04 UTC, lschlesinger commented on Sources/Apodini/Semantic Model Builder/Protobuffer/Model+EnrichedInfo.swift
> +    func compatibleGenericName() throws -> String {
I just today did the same task for OAS: handling type names including incompatible characters, such as `<`, `>`, and `,` 😄 ! I tried to not hide the information by what these characters are replaced, through defining an enum including some constants:
```swift
enum OpenAPISchemaConstants {
    static let replaceAngleBracket = "_"
    static let replaceCommaSeparation = "-comma-"
}
```
This also allowed by to use these properties in the tests and not getting out of sync in case I want to change something! Maybe you find that useful, too.
I came up with this enum solution for constants, as this is the only format swiftlint will not complain about.

2021-01-25 15:04 UTC, lschlesinger commented on Sources/Apodini/Semantic Model Builder/Protobuffer/Model+EnrichedInfo.swift
> +    func compatibleGenericName() throws -> String {
Additionally, I used regex, to catch cases where `X, Y` lacks the whitespace: `X,Y`. So I use:
```swift
.replacingOccurrences(of: "(\\,\\s|\\,)", with: OpenAPISchemaConstants.replaceCommaSeparation, options: .regularExpression)
```

2021-01-25 15:04 UTC, lschlesinger commented on Sources/Apodini/Utilities/Tree.swift
> +    func collectValues() -> Set<T> where T: Hashable {
I find this very useful!! And as I already sneaked a peek at that PR before, I already incorporated this in my work by simply copying this to check if it solves my task - it worked. So I am happy to find this in develop, soon 👍

2021-01-25 15:04 UTC, lschlesinger commented on Sources/Apodini/Semantic Model Builder/Protobuffer/ProtobufferInterfaceExporter.swift
> +        try EnrichedInfo.node(type)
I encountered that I need to do this "editing process" recursively, in order to catch the cases, where collection types are nested. The related PR #179 is not ready yet, but I think it is enough for you to identify if you might run in the same problems. The associated Issue #178 hopefully help to understand, what I try to reach in the PR.

2021-01-25 19:00 UTC, nityanandaz commented on Sources/Apodini/Semantic Model Builder/Protobuffer/Model+EnrichedInfo.swift
> +    func compatibleGenericName() throws -> String {
Did you catch any cases were the space is actually missing? I expect this behavior to be stable 🙂

2021-01-25 19:06 UTC, nityanandaz commented on Sources/Apodini/Semantic Model Builder/Protobuffer/ProtobufferInterfaceExporter.swift
> +        try EnrichedInfo.node(type)
I am also working/experimenting on a solution for this: https://github.com/Apodini/Apodini/blob/156cba7df7d1dbceb877cf95fd463078535770b1/Sources/Apodini/Semantic%20Model%20Builder/Model/TypeReflection/EnrichedInfo.swift#L148 on https://github.com/Apodini/Apodini/tree/refactor/EnrichedInfo.node

I will look into it 👍

2021-01-25 20:10 UTC, lschlesinger commented on Sources/Apodini/Semantic Model Builder/Protobuffer/Model+EnrichedInfo.swift
> +    func compatibleGenericName() throws -> String {
I thought I had seen it somewhere in the debugger... but I just checked again, you're right!

2021-01-27 15:13 UTC, moritzschuell approved these changes
Looks good to me 👍 
This is a big step forward, thank you!

2021-01-28 10:39 UTC, merged