Adjustable Configuration for Apodini
Apodini/Apodini pull request #19
Opened 2020-11-23 08:53 UTC by hendesi

**Implementation**
This pull request contains changes by @hendesi and @awoc to the Apodini framework, which enable the enduser to define and use configurations for the Apodini system. The configuration structure behaves similar to the one of the components. This allows for a customisation by the user without exposing the internals of Apodini to the outside. The user can add various Configuration Object in the 
```
var configuration: some Configuration {
...
}
```

Configuration Objects need to conform to the `Configuration` protocol and need to implement the `func configure(_ app:Application)` method. The user can implement additional functions, which need to return `Self`. These can then be appended to the configuration object similar to the modifiers of components. The configurations are loaded after registering the semantic models and before the start of the server.

Example:

```
var configuration: some Configuration {
        DatabaseConfiguration(.mongo)
            .connectionString("mongodb://localhost:27017/vapor_database")
            .addMigrations(CreateBird())
    }
```

Example additional methods:
```
public func connectionString(_ string: String) -> Self {
        self.connectionString = string
        return self
    }
```

**Problems we faced**
Currently the `var configuration: some Configuration {}`needs to be implemented with at least one Configuration Object, otherwise the server startup will fail due to conformation to `Never`. Since the Configuration structure is very similar to the one of the components, we would face the same problem when removing `var content: some Component`. This is something we need to further investigate as users should still be able to use Apodini despite not implementing configuration.

2020-11-23 12:11 UTC, nerdsupremacist submitted a review, later dismissed
# Great Job!

Thanks for making this better ;)
I left a couple of nits ("not important though" comments)
Please deal with the lint errors and then we can merge this

## Future Work
I'm thinking that we should consider moving towards additional type safety in the Component DSL. Perhaps we should do that here as well. I'll start a branch with that as soon as we merge this ;)

2020-11-23 12:11 UTC, nerdsupremacist commented on Sources/Apodini/Configurations/AnyConfigurationCollection.swift
> +//
nit: Can we please remove the headers? Not a big fan of it

2020-11-23 12:11 UTC, nerdsupremacist commented on Sources/Apodini/Configurations/Configurator.swift
> +    private(set) var app: Application
nit: The configurator couples the DSL directly to Vapor. We need to start considering ways to decouple it. 
But that seems like it's out of scope for this PR ;)

2020-11-23 14:25 UTC, awoc commented on Sources/Apodini/Configurations/APNSConfiguration.swift
> +    case p8(path: String, keyIdentifier: JWTKit.JWKIdentifier, teamIdentifier: String)
Are too short enum element names really a problem or can we just change the swiftlint rule for this? I think using the file extension as the enum element name makes it clear which case to use

2020-11-23 16:33 UTC, bauer-andreas commented on Sources/Apodini/Configurations/AnyConfigurationCollection.swift
> +    }
Judging by `ConfigurationGroup.configurable` and the current implementation of `Configurator` which is using the `ContextNode` as well ( mimicking what the `SyntaxTreeVisitor` does for `Component`s), the current code might create the same issue described in https://github.com/Apodini/Apodini/issues/12 (which is trying to be fixed with https://github.com/Apodini/Apodini/pull/13).
The issue really is missing `Configurator.enter` and `Configurator.exit` calls in the marked code section.

Is there any intention to use `ContextNode` for future Configurations? Looking into the already provided implementation it doesn't seem like (there isn't really any possibility to use it really).

2020-11-23 16:57 UTC, PSchmiedmayer commented on Sources/Apodini/Configurations/APNSConfiguration.swift
> +    case p8(path: String, keyIdentifier: JWTKit.JWKIdentifier, teamIdentifier: String)
I think we can make an exception for this specific case on our .swiftLint file or just add a SwiftLint disable command here.

2020-11-27 17:23 UTC, awoc commented
@PSchmiedmayer @nerdsupremacist We reduced the complexity and resolved the problem with the missing `configuration` property at server startup. This slightly changed the DSL from ```swift var configuration: some Configuration {}``` to ```swift var configuration:  Configuration {}```, therefore, not using an opaque type.

2020-12-02 08:01 UTC, nerdsupremacist submitted a review, later dismissed

2020-12-07 22:53 UTC, nerdsupremacist approved these changes, later dismissed

2020-12-07 22:53 UTC, nerdsupremacist commented on Sources/Apodini/Configurations/APNSConfiguration.swift
> +    public func configure(_ app: Application) {
Depending on what get's merged first: this or #32 we might habe to do some decoupling here as well

2020-12-07 23:00 UTC, PSchmiedmayer requested changes
I only had a single comment regarding an unused variable. Apart from this the PR looks great, you can merge it after fixing the small issue.

2020-12-07 23:00 UTC, PSchmiedmayer commented on Sources/Apodini/Configurations/DatabaseConfiguration.swift
> +        var databaseFactory: Fluent.DatabaseConfigurationFactory?
```suggestion
```
This property is not needed, feel free to remove it here.

2020-12-08 10:01 UTC, PSchmiedmayer approved these changes

2020-12-08 13:44 UTC, merged