Adds Tuple Component and expands maximum of components to 100
Apodini/Apodini pull request #20
Opened 2020-11-23 13:46 UTC by nerdsupremacist

## Summary
This PR seeks to add some extra type information by no longer using type erasure in the Component Builder by default. So I
- Deleted AnyComponentCollection
- Added TupleComponent with the generic parameter that keeps the component type information
- Moved the component builder to a gyb (generate your boilerplate) file and increased the number of maximum blocks to 100.

Closes #16 

## Test Plan
All previous tests pass ;)

2020-11-23 16:53 UTC, PSchmiedmayer requested changes
Thanks for the improvement! This will help us a lot to get more type information out of the DSL tree. Using gyb sounds like a good idea!

Unfortunately there seems to be a build issue on linux at the moment when applying your changes. Can you take a look at this before we merge the PR. In addition there are some new changes and documentation on develop that can also help you to resolve your SwiftLint issues 👍

2020-11-29 22:38 UTC, PSchmiedmayer requested changes
@nerdsupremacist It seems that the tests about `Group` `Component`s are still failing after replacing the `AnyComponentCollection` with a `TupleComponent`. I suspect that this is due to the changed `visit` function in the `TupleComponent`.
I would also suggest to add some additional regression tests about visiting Group components in the PR too.

2020-11-30 10:28 UTC, nerdsupremacist commented
@PSchmiedmayer Ah I see I understood enterCollectionItem wrong. It's fixed now

2020-12-01 14:45 UTC, PSchmiedmayer approved these changes

2020-12-01 15:08 UTC, merged