Allow user to enable HTTP/2 and TLS
Apodini/Apodini pull request #24
Opened 2020-11-25 09:10 UTC by moritzschuell

This PR adds two command line options, `--cert` and `--key`, that allow the user to specify a certificate and a private key. If the user provides both options, the server will enable HTTP/1, HTTP/2 and TLS. Otherwise, the server will operate as before using only HTTP/1 without TLS.

**Why?**
We need the possibility to use HTTP/2 and TLS to be able to communicate with the gRPC clients that are generated from `.proto` files using the `protoc` compiler. So, if the user wants the exported gRPC interface of Apodini to work with the generated client code, he has to provide both `--cert` and `--key` to the server. 

If the user does not provide them, he can still use the exported gRPC interface via REST calls, and provide the encoded message in the body (as of now, as a result of how the `GRPCMiddleware` is planned to be "catching" gRPC requests from Vapor). 

**Note**
I had to adjust how we detect the app environment from...
```swift
var env = try Environment.detect()
```
... to...
```swift
let environmentName = try Environment.detect().name
var env = Environment(name: environmentName, arguments: ["vapor"])
```
It seems like the auto-detected environment is also parsing the command line arguments, which causes interference with the usage of `ArgumentParser`. 
See this issue: https://github.com/vapor/vapor/issues/2385

2020-11-25 09:53 UTC, awoc commented
I think in the future you can also write a `Configuration` once PR #19 is merged which might integrate better into the DSL. But I guess this would be another PR :)

2020-11-27 08:09 UTC, moritzschuell commented
Closing this for now, until #19 is merged. I will rework this PR to use the new configuration functionality then.

2020-12-05 20:59 UTC, moritzschuell commented
Reopening, I rewrote the HTTP/2 and TLS configuration for the new config approach.

2020-12-08 22:04 UTC, awoc requested changes
I noted down some minor remarks. Otherwise, it looks good to me 👍

2020-12-08 22:04 UTC, awoc commented on Package.swift
> -                "Components/ComponentBuilder.swift.gyb"
I wouldn't delete this part. This will lead to a warning in the build jobs and in Xcode.

2020-12-08 22:04 UTC, awoc commented on Sources/Apodini/Configurations/HTTP2Configuration.swift
> +        } catch { }
In case of a failure, I think it would be nice to also indicate this to an user in form of a print statement or something else.

2020-12-09 09:37 UTC, awoc approved these changes

2020-12-09 21:23 UTC, hendesi approved these changes
I have nothing to add. Looks good to me 👍

2020-12-10 07:25 UTC, merged