Graphql Semantic Builder Info md File
Apodini/Apodini pull request #45
Opened 2020-12-07 17:24 UTC by sadikekin

This PR contains the mapping of the Aponni DSL to GraphQl exporter.

2021-01-10 13:00 UTC, sadikekin commented
Hey @nerdsupremacist, Do you have any comments about this documentation?

2021-01-18 15:12 UTC, nerdsupremacist requested changes

2021-01-18 15:12 UTC, nerdsupremacist commented on Documentation/SemanticBuilders/GraphQLSemanticBuilder.md
> +  Book() : Book
The field should probably have the same casing as in the group. And I think the Book is non null:

```graphql
book: Book!
```

2021-01-18 15:12 UTC, nerdsupremacist commented on Documentation/SemanticBuilders/GraphQLSemanticBuilder.md
> +    userId: Int!
the fields on user should probably be named like in the User Struct:

```graphql
type User {
    id: Int!
    name: String!
}
```

2021-01-18 18:04 UTC, nerdsupremacist approved these changes

2021-01-19 08:44 UTC, merged