Added Database To @Environment
Apodini/Apodini pull request #84
Opened 2020-12-27 20:23 UTC by hendesi

# Added database to @environment

## :recycle: Current situation
Currently the database can be access by `@_Database` which is a separate property wrapper and `RequestInjectable`. 
Current usage:
```
@_Database
var database: Fluent.Database
```

## :bulb: Proposed solution
Use the `@Environment` property introduced by #40. This changes the code to:
```
 @Apodini.Environment(\.database)
        var database: Fluent.Database
``` 

### Problem that is solved
This change removes the `Database` property/file as we want to move away from separate property wrappers and make use of the existing `@Environment` infrastructure. Furthermore it allows a way to provide a default database of the new request introduced by #81. The current approach would no longer work with the refactoring by #81.

### Implications
No real implications beside the refactoring from `@_Database` to `@Apodini.Environment(\.database)`.

## :heavy_plus_sign: Additional Information
--

### Related PRs
PRs affected by the change:
#70 
#81 

### Testing
No new tests, but I refactored tests that use the database.

### Reviewer Nudging
One could start looking at the `DatabaseConfiguration` where the environment value is set and then at `CustomComponentTests` to see the usage.

2020-12-28 17:01 UTC, tgymnich requested changes
Could you also remove the database property from `Request`?

2020-12-29 00:01 UTC, tgymnich approved these changes, later dismissed
👍

2020-12-29 20:08 UTC, hendesi commented
@tgymnich Could you please approve this again? Github automatically removes review after a new commit

2020-12-29 20:10 UTC, tgymnich approved these changes

2021-01-01 19:56 UTC, merged